In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\hp\Documents\toys\data\raw\orders.csv");
df1 = pd.read_csv(r"C:\Users\hp\Documents\toys\data\raw\order_items.csv");
df2 = pd.read_csv(r"C:\Users\hp\Documents\toys\data\raw\products.csv");
df3 = pd.read_csv(r"C:\Users\hp\Documents\toys\data\raw\order_item_refunds.csv");
df4 = pd.read_csv(r"C:\Users\hp\Documents\toys\data\raw\website_pageviews.csv");
df5 = pd.read_csv(r"C:\Users\hp\Documents\toys\data\raw\website_sessions.csv");

In [3]:
df.shape

(32313, 8)

In [4]:
df.head()

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

In [5]:
df.isna().sum()

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

In [6]:
df.describe()

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215691.622629,1.392474,1.238666,59.991636,22.355406
std,9328.103961,132427.649842,108402.203189,0.732277,0.426274,17.808771,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,124135.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221461.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,109.980000,41.980000

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns = df.columns.str.strip().str.lower()

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  str
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), str(1)
memory usage: 2.0 MB

In [10]:
df = df.rename(columns={"cogs_usd":"cost_price"})

In [12]:
df = df.rename(columns={"price_usd":"selling_price"})

In [13]:
df = df.rename(columns={"created_at":"order_date"})

In [15]:
df["order_date"] = pd.to_datetime(df["order_date"],
                                format="mixed",
                                dayfirst=True,
                                errors='coerce')

In [17]:
df.head()

,order_id,order_date,website_session_id,user_id,primary_product_id,items_purchased,selling_price,cost_price
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

In [18]:
df.to_csv("C:/Users/hp/Documents/toys/data/clean/orders.csv",index=False)

In [19]:
df1.head()

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

In [20]:
df1.isna().sum()

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

In [21]:
df1.duplicated().sum()

np.int64(0)

In [22]:
df1.shape

(40025, 7)

In [23]:
df1.info();

<class 'pandas.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  str
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), str(1)
memory usage: 2.1 MB

In [27]:
df1 = df1.rename(columns={
    "cogs_usd":"cost_price",
    "price_usd":"selling_price",
    "created_at":"item_date"
})

In [29]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   item_date        40025 non-null  str
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   selling_price    40025 non-null  float64
 6   cost_price       40025 non-null  float64
dtypes: float64(2), int64(4), str(1)
memory usage: 2.1 MB

In [30]:
df1["item_date"] = pd.to_datetime(df1["item_date"],
                                  format="mixed",
                                  dayfirst=True,
                                  errors='coerce')

In [31]:
df1.to_csv("C:/Users/hp/Documents/toys/data/clean/order_items.csv",index=False)

In [32]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   created_at    4 non-null      str
 2   product_name  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [33]:
df2.isna().sum()

product_id      0
created_at      0
product_name    0
dtype: int64

In [34]:
df2.duplicated().sum()

np.int64(0)

In [35]:
df2.head()

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

In [36]:
df2.columns = df2.columns.str.strip().str.lower()

In [37]:
df2["product_name"] = df2["product_name"].str.strip()

In [39]:
df2["product_name"].value_counts()

product_name
The Original Mr. Fuzzy        1
The Forever Love Bear         1
The Birthday Sugar Panda      1
The Hudson River Mini bear    1
Name: count, dtype: int64

In [40]:
df2 = df2.rename(columns={"created_at":"product_launch_date"})
df2["product_launch_date"] = pd.to_datetime(df2["product_launch_date"],
                                            format="mixed",
                                            dayfirst=True,
                                            errors='coerce')

In [41]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           4 non-null      int64
 1   product_launch_date  4 non-null      datetime64[us]
 2   product_name         4 non-null      str
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 228.0 bytes

In [59]:
df2.to_csv("C:/Users/hp/Documents/toys/data/clean/products.csv",index=False)

In [43]:
df3.shape

(1731, 5)

In [44]:
df3.head()

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

In [45]:
df3.isna().sum()

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

In [46]:
df3.duplicated().sum()

np.int64(0)

In [47]:
df3 = df3.rename(columns={
    "created_at":"refund_issue_date",
    "refund_amount_usd":"refund_amount"
})

In [48]:
df3["refund_issue_date"]=pd.to_datetime(df3["refund_issue_date"],
 format='mixed',
 dayfirst=True,
 errors='coerce')

In [49]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   refund_issue_date     1731 non-null   datetime64[us]
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount         1731 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(3)
memory usage: 67.7 KB

In [58]:
df3.to_csv("C:/Users/hp/Documents/toys/data/clean/order_item_refunds.csv",index=False)

In [51]:
df4.head()

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home
3                    4  2012-03-19 08:37:33                   4        /home
4                    5  2012-03-19 09:00:55                   5        /home

In [1]:
df4.info()

NameError: name 'df4' is not defined

In [ ]:
df4.duplicated().sum()

np.int64(0)

In [55]:
df4["created_at"] = pd.to_datetime(df4["created_at"],
                                   format="mixed",
                                   dayfirst=True,
                                   errors='coerce')

In [56]:
df4.to_csv("C:/Users/hp/Documents/toys/data/clean/website_pageviews.csv",index=False);

In [60]:
df5.head()

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [61]:
df5.isna().sum()

website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

In [62]:
df5.duplicated().sum()

np.int64(0)

In [64]:
missing_summary = pd.DataFrame({
    "missing_value":df5.isna().sum(),
    "missing_percent":(df5.isna().mean())*100.0
})
missing_summary

                    missing_value  missing_percent
website_session_id              0         0.000000
created_at                      0         0.000000
user_id                         0         0.000000
is_repeat_session               0         0.000000
utm_source                  83328        17.621719
utm_campaign                83328        17.621719
utm_content                 83328        17.621719
device_type                     0         0.000000
http_referer                39917         8.441414

In [65]:
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  str
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  str
 5   utm_campaign        389543 non-null  str
 6   utm_content         389543 non-null  str
 7   device_type         472871 non-null  str
 8   http_referer        432954 non-null  str
dtypes: int64(3), str(6)
memory usage: 32.5 MB

In [69]:
df5["utm_campaign"].unique()

<StringArray>
['nonbrand', nan, 'brand', 'pilot', 'desktop_targeted']
Length: 5, dtype: str

In [71]:
df5["utm_content"].value_counts(dropna=False)

utm_content
g_ad_1         282706
NaN             83328
b_ad_1          54909
g_ad_2          33329
b_ad_2           7914
social_ad_2      5590
social_ad_1      5095
Name: count, dtype: int64

In [72]:
df5["utm_source"].value_counts(dropna=False)

utm_source
gsearch       316035
NaN            83328
bsearch        62823
socialbook     10685
Name: count, dtype: int64

In [73]:
df5["created_at"] = pd.to_datetime(df5["created_at"],
                                   format="mixed",
                                   dayfirst=True,
                                   errors='coerce')

In [74]:
df5.to_csv("C:/Users/hp/Documents/toys/data/clean/website_sessions.csv",index=False);

In [1]:
import pandas as pd ;
import numpy as np ;

In [3]:
df5=pd.read_csv ("C:/Users/hp/Documents/toys/data/clean/website_sessions.csv",parse_dates=["created_at"]);

In [4]:
df5.isna().sum()

website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

In [5]:
df5.isna().mean()

website_session_id    0.000000
created_at            0.000000
user_id               0.000000
is_repeat_session     0.000000
utm_source            0.176217
utm_campaign          0.176217
utm_content           0.176217
device_type           0.000000
http_referer          0.084414
dtype: float64

In [6]:
df5["utm_campaign"].mode()

0    nonbrand
Name: utm_campaign, dtype: str

In [10]:
mode_value = df5["utm_campaign"].mode()[0]
df5["utm_campaign"] = df5["utm_campaign"].fillna(mode_value)

In [11]:
df5['utm_campaign'].isna().sum()

np.int64(0)

In [12]:
category = ["utm_source","utm_content","http_referer"]
for col in category:
    mode_values = df5[col].mode()[0]
    df5[col]=df5[col].fillna(mode_values)

In [13]:
df5.isna().sum()

website_session_id    0
created_at            0
user_id               0
is_repeat_session     0
utm_source            0
utm_campaign          0
utm_content           0
device_type           0
http_referer          0
dtype: int64

In [14]:
df5.to_csv("C:/Users/hp/Documents/toys/data/clean/website_sessions.csv",index=False);