In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/raw_data/2019-Oct.csv")

In [3]:
df.shape

(4102283, 9)

In [4]:
df.head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
5,2019-10-01 00:00:16 UTC,cart,5857269,1487580005134238553,NaN,runail,2.62,430174032,73dea1e7-664e-43f4-8b30-d32b9d5af04f
6,2019-10-01 00:00:19 UTC,cart,5739055,1487580008246412266,NaN,kapous,4.75,377667011,81326ac6-daa4-4f0a-b488-fd0956a78733
7,2019-10-01 00:00:24 UTC,cart,5825598,1487580009445982239,NaN,NaN,0.56,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
8,2019-10-01 00:00:25 UTC,cart,5698989,1487580006317032337,NaN,NaN,1.27,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
9,2019-10-01 00:00:26 UTC,view,5875317,2029082628195353599,NaN,NaN,1.59,474232307,445f2b74-5e4c-427e-b7fa-6e0a28b156fe

In [5]:
df.tail()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
4102278,2019-10-31 23:59:25 UTC,remove_from_cart,5848062,1526733091857498510,NaN,NaN,9.21,429913900,2f0bff3c-252f-4fe6-afcd-5d8a6a92839a
4102279,2019-10-31 23:59:30 UTC,view,5885631,1783999064103190764,NaN,NaN,15.48,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
4102280,2019-10-31 23:59:34 UTC,view,5784898,1487580009143992338,NaN,NaN,1.78,564441099,8cbf1746-2d46-4169-afb1-b5fa38ee1ba4
4102281,2019-10-31 23:59:36 UTC,view,5870838,1487580007675986893,NaN,milv,0.79,429913900,2f0bff3c-252f-4fe6-afcd-5d8a6a92839a
4102282,2019-10-31 23:59:54 UTC,view,59996,1487580012927254698,NaN,NaN,4.13,566280798,4eaf7c71-e8bf-4ea6-b719-eca144466eb3

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4102283 entries, 0 to 4102282
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 281.7 MB

In [7]:
df.describe()

         product_id   category_id         price       user_id
count  4.102283e+06  4.102283e+06  4.102283e+06  4.102283e+06
mean   5.468464e+06  1.545652e+18  8.534920e+00  5.013416e+08
std    1.321863e+06  1.563666e+17  1.913315e+01  8.171257e+07
min    3.752000e+03  1.487580e+18 -7.937000e+01  4.103071e+06
25%    5.723489e+06  1.487580e+18  2.140000e+00  4.692921e+08
50%    5.809115e+06  1.487580e+18  4.110000e+00  5.389695e+08
75%    5.850322e+06  1.487580e+18  7.140000e+00  5.575029e+08
max    5.900470e+06  2.195085e+18  3.076000e+02  5.662808e+08

In [8]:
df.isna().sum()

event_time             0
event_type             0
product_id             0
category_id            0
category_code    4034806
brand            1659261
price                  0
user_id                0
user_session         637
dtype: int64

In [9]:
missing_summary = pd.DataFrame({
    "missing_value":df.isna().sum(),
    "missing_percent":(df.isna().mean()*100.0).round(2)
})
missing_summary

               missing_value  missing_percent
event_time                 0             0.00
event_type                 0             0.00
product_id                 0             0.00
category_id                0             0.00
category_code        4034806            98.36
brand                1659261            40.45
price                      0             0.00
user_id                    0             0.00
user_session             637             0.02

In [10]:
df.dtypes

event_time           str
event_type           str
product_id         int64
category_id        int64
category_code        str
brand                str
price            float64
user_id            int64
user_session         str
dtype: object

In [11]:
df["event_time"]=pd.to_datetime(df["event_time"],
                                format='mixed',
                                dayfirst=True,
                                errors='coerce')

In [12]:
df["event_time"].dtypes

datetime64[us, UTC]

In [13]:
df.duplicated().sum()

np.int64(213155)

In [14]:
df[df.duplicated()]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
13,2019-01-10 00:00:30+00:00,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
30,2019-01-10 00:01:05+00:00,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
36,2019-01-10 00:01:07+00:00,remove_from_cart,5312,1487580009471148064,NaN,runail,1.27,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
38,2019-01-10 00:01:10+00:00,remove_from_cart,5823915,1487580007432717250,NaN,milv,1.59,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
51,2019-01-10 00:01:24+00:00,remove_from_cart,5664641,1487580011425693811,NaN,NaN,0.70,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
...,...,...,...,...,...,...,...,...,...
4102134,2019-10-31 23:50:32+00:00,remove_from_cart,5682344,1487580008590345208,NaN,zinger,2.22,514649199,dd20e3bf-021f-4633-a9c7-18b6158b2006
4102223,2019-10-31 23:55:52+00:00,remove_from_cart,4654,1487580011157258342,NaN,runail,0.37,562691482,9025c3a5-9c56-49c4-9d3d-95a6c15b69a3
4102232,2019-10-31 23:56:18+00:00,remove_from_cart,5834736,1487580009445982239,NaN,NaN,3.02,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
4102246,2019-10-31 23:56:46+00:00,remove_from_cart,5776516,1487580009445982239,NaN,NaN,7.14,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
4102250,2019-10-31 23:56:52+00:00,remove_from_cart,5834737,1487580009445982239,NaN,NaN,1.98,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb

In [15]:
df[df.duplicated(keep=False)].sort_values(["event_time","user_session"]).head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
12,2019-01-10 00:00:30+00:00,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
13,2019-01-10 00:00:30+00:00,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
29,2019-01-10 00:01:05+00:00,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
30,2019-01-10 00:01:05+00:00,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
34,2019-01-10 00:01:07+00:00,remove_from_cart,5312,1487580009471148064,NaN,runail,1.27,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486

In [16]:
df = df.drop_duplicates()

In [17]:
print(df.duplicated().sum())

0

In [18]:
df = df.drop("category_code",axis=1)

In [19]:
df.head()

,event_time,event_type,product_id,category_id,brand,price,user_id,user_session
0,2019-01-10 00:00:00+00:00,cart,5773203,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-01-10 00:00:03+00:00,cart,5773353,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-01-10 00:00:07+00:00,cart,5881589,2151191071051219817,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-01-10 00:00:07+00:00,cart,5723490,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-01-10 00:00:15+00:00,cart,5881449,1487580013522845895,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [20]:
df["brand"].value_counts(dropna=False).head(20)

brand
NaN          1571314
runail        287149
irisk         213301
masura        182845
grattol       125856
bpw.style     107895
ingarden       84309
estel          62463
pole           57317
kapous         56077
uno            46142
italwax        44381
jessnail       43936
cnd            42920
bluesky        41630
concept        40111
freedecor      39044
haruyama       38686
milv           33409
domix          32600
Name: count, dtype: int64

In [21]:
df["brand"].isna().mean()*100.0

np.float64(40.40273295196249)

In [22]:
df["brand"] = df["brand"].str.replace(".","",regex=False)

In [23]:
df["brand"].value_counts(dropna=False).head(20)

brand
NaN          1571314
runail        287149
irisk         213301
masura        182845
grattol       125856
bpwstyle      107895
ingarden       84309
estel          62463
pole           57317
kapous         56077
uno            46142
italwax        44381
jessnail       43936
cnd            42920
bluesky        41630
concept        40111
freedecor      39044
haruyama       38686
milv           33409
domix          32600
Name: count, dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df["brand"] = df["brand"].fillna("unknown")

In [26]:
df.isna().sum()

event_time        0
event_type        0
product_id        0
category_id       0
brand             0
price             0
user_id           0
user_session    574
dtype: int64

In [27]:
df.dropna(subset=["user_session"],inplace=True)

In [28]:
df["user_session"].isna().sum()

np.int64(0)

In [29]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id', 'brand',
       'price', 'user_id', 'user_session'],
      dtype='str')

In [30]:
df.columns = df.columns.str.strip().str.lower()

In [31]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id', 'brand',
       'price', 'user_id', 'user_session'],
      dtype='str')

In [34]:
df["event_type"].value_counts()

event_type
view                1862047
cart                1203756
remove_from_cart     577470
purchase             245281
Name: count, dtype: int64

In [36]:
(df["price"]<0).sum()

np.int64(20)

In [37]:
df[df["price"]<0][
        ["event_type", "product_id", "price", "user_id", "user_session"]

]

,event_type,product_id,price,user_id,user_session
112860,purchase,5716857,-23.81,552507528,dcdd60c6-1a70-442d-bfb2-0252879054ad
198302,purchase,5716855,-7.94,550375225,5ddec778-9464-4514-914d-be7b751b8e2c
436918,purchase,5716859,-47.62,555414763,479149eb-1807-4178-8f6b-87c642350735
443204,purchase,5670257,-15.87,556383221,4333d203-bc4d-4d0d-a6e1-0ea3a97a28c1
1295556,purchase,5716855,-7.94,514562574,fed2aeb4-0c75-44f7-9ca8-1a8be8214779
1426186,purchase,5716855,-7.94,558797258,a406cf28-f04b-4361-8e6a-c62d36045e07
1519246,purchase,5716859,-47.62,543647038,85e11d74-6583-4eab-b50c-ff86dbb25d97
1783312,purchase,5716857,-23.81,559820267,f178c995-f004-4040-b26d-b1cca0f9657d
1924072,purchase,5716861,-79.37,541122983,b60f777d-afca-4299-8548-273b810d6130
2143762,purchase,5716857,-23.81,461943726,beefa8fb-a3d1-48ca-97e9-9c95b05ee997
2286569,purchase,5670257,-15.87,557964596,4f4ee4c7-8081-41f1-91bb-ea74a7f1669d
2418566,purchase,5670257,-15.87,558697902,8ad665ca-1cd9-46a5-a95c-996fe3afa08f
3056821,purchase,5670257,-15.87,563375190,e925f825-c62a-4e0d-bf80-884ca1c66f41
3135434,purchase,5716859,-47.62,545859098,95ed1875-cb64-443d-90bb-17d0dc596c10
3502423,purchase,5716859,-47.62,564627373,81d564e9-55b3-4929-9132-6353cab08a97
3593034,purchase,5670257,-15.87,564602671,527638c5-23bb-98f7-3776-6278c0776b84
3608726,purchase,5716857,-23.81,385939606,2255291d-8060-4ce9-934c-458a3bd0b944
3670216,purchase,5670257,-15.87,562756002,6f5bc29c-5ea9-4157-9d9e-7ceabb1e993c
3798007,purchase,5716857,-23.81,554081558,4b84a8f9-97d7-4eb1-b120-7b34ddfe9a85
3807737,purchase,5716859,-47.62,546120591,31cd4767-fadb-43ea-8a3f-f8769dd83fcf

In [38]:
negative_products = df.loc[df["price"] < 0, "product_id"].unique()

df[df["product_id"].isin(negative_products)][
    ["event_type", "product_id", "price"]
].sort_values("product_id")

        event_type  product_id  price
443204    purchase     5670257 -15.87
3593034   purchase     5670257 -15.87
2286569   purchase     5670257 -15.87
2418566   purchase     5670257 -15.87
3056821   purchase     5670257 -15.87
3670216   purchase     5670257 -15.87
1426186   purchase     5716855  -7.94
198302    purchase     5716855  -7.94
1295556   purchase     5716855  -7.94
2143762   purchase     5716857 -23.81
112860    purchase     5716857 -23.81
1783312   purchase     5716857 -23.81
3608726   purchase     5716857 -23.81
3798007   purchase     5716857 -23.81
1519246   purchase     5716859 -47.62
436918    purchase     5716859 -47.62
3135434   purchase     5716859 -47.62
3502423   purchase     5716859 -47.62
3807737   purchase     5716859 -47.62
1924072   purchase     5716861 -79.37

In [39]:
df.loc[df["price"]<0,"price"]=np.nan

In [40]:
df["price"]=df["price"].fillna(df.groupby("product_id")["price"].transform("median"))

In [42]:
df["price"].isna().sum()

np.int64(20)

In [43]:
df["event_time_ist"] = df["event_time"].dt.tz_convert("Asia/Kolkata");
df["month"] = df["event_time_ist"].dt.month
df["day"] = df["event_time_ist"].dt.day
df["day_of_week"] = df["event_time_ist"].dt.day_name()
df["hour"] = df["event_time_ist"].dt.hour
df["minute"] = df["event_time_ist"].dt.minute

In [44]:
df.describe()

,product_id,category_id,price,user_id,month,day,hour,minute
count,3.888554e+06,3.888554e+06,3.888534e+06,3.888554e+06,3.888554e+06,3.888554e+06,3.888554e+06,3.888554e+06
mean,5.466209e+06,1.545763e+18,8.725619e+00,5.016925e+08,8.454244e+00,1.702717e+01,1.294747e+01,2.942827e+01
std,1.326402e+06,1.565777e+17,1.949261e+01,8.196638e+07,2.856145e+00,7.276581e+00,7.293869e+00,1.731002e+01
min,3.752000e+03,1.487580e+18,0.000000e+00,4.103071e+06,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,5.723488e+06,1.487580e+18,2.220000e+00,4.697497e+08,7.000000e+00,1.000000e+01,8.000000e+00,1.400000e+01
50%,5.809131e+06,1.487580e+18,4.110000e+00,5.396801e+08,1.000000e+01,1.500000e+01,1.500000e+01,2.900000e+01
75%,5.850497e+06,1.487580e+18,7.140000e+00,5.575520e+08,1.000000e+01,2.300000e+01,1.900000e+01,4.400000e+01
max,5.900470e+06,2.195085e+18,3.076000e+02,5.662808e+08,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01

In [45]:
df.head()

,event_time,event_type,product_id,category_id,brand,price,user_id,user_session,event_time_ist,month,day,day_of_week,hour,minute
0,2019-01-10 00:00:00+00:00,cart,5773203,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:00+05:30,1,10,Thursday,5,30
1,2019-01-10 00:00:03+00:00,cart,5773353,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:03+05:30,1,10,Thursday,5,30
2,2019-01-10 00:00:07+00:00,cart,5881589,2151191071051219817,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2019-01-10 05:30:07+05:30,1,10,Thursday,5,30
3,2019-01-10 00:00:07+00:00,cart,5723490,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:07+05:30,1,10,Thursday,5,30
4,2019-01-10 00:00:15+00:00,cart,5881449,1487580013522845895,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2019-01-10 05:30:15+05:30,1,10,Thursday,5,30

In [47]:
df = df.drop("event_time",axis=1)

In [48]:
df.head()

,event_type,product_id,category_id,brand,price,user_id,user_session,event_time_ist,month,day,day_of_week,hour,minute
0,cart,5773203,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:00+05:30,1,10,Thursday,5,30
1,cart,5773353,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:03+05:30,1,10,Thursday,5,30
2,cart,5881589,2151191071051219817,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2019-01-10 05:30:07+05:30,1,10,Thursday,5,30
3,cart,5723490,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:07+05:30,1,10,Thursday,5,30
4,cart,5881449,1487580013522845895,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2019-01-10 05:30:15+05:30,1,10,Thursday,5,30

In [49]:
df.info()

<class 'pandas.DataFrame'>
Index: 3888554 entries, 0 to 4102282
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   event_type      str
 1   product_id      int64
 2   category_id     int64
 3   brand           str
 4   price           float64
 5   user_id         int64
 6   user_session    str
 7   event_time_ist  datetime64[us, Asia/Kolkata]
 8   month           int32
 9   day             int32
 10  day_of_week     str
 11  hour            int32
 12  minute          int32
dtypes: datetime64[us, Asia/Kolkata](1), float64(1), int32(4), int64(3), str(4)
memory usage: 356.0 MB

In [ ]:
df.to_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Oct.csv",index=False)

In [53]:
df = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Oct.csv")

In [54]:
df.head()

,event_type,product_id,category_id,brand,price,user_id,user_session,event_time_ist,month,day,day_of_week,hour,minute
0,cart,5773203,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:00+05:30,1,10,Thursday,5,30
1,cart,5773353,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:03+05:30,1,10,Thursday,5,30
2,cart,5881589,2151191071051219817,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2019-01-10 05:30:07+05:30,1,10,Thursday,5,30
3,cart,5723490,1487580005134238553,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,2019-01-10 05:30:07+05:30,1,10,Thursday,5,30
4,cart,5881449,1487580013522845895,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2019-01-10 05:30:15+05:30,1,10,Thursday,5,30

## import files

In [2]:
df1 = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/raw_data/2019-Nov.csv");
df2 = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/raw_data/2019-Dec.csv");
df3 = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/raw_data/2020-Jan.csv");
df4 = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/raw_data/2020-Feb.csv");

In [3]:
df1.shape

(4635837, 9)

In [4]:
df1.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:02 UTC,view,5802432,1487580009286598681,NaN,NaN,0.32,562076640,09fafd6c-6c99-46b1-834f-33527f4de241
1,2019-11-01 00:00:09 UTC,cart,5844397,1487580006317032337,NaN,NaN,2.38,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
2,2019-11-01 00:00:10 UTC,view,5837166,1783999064103190764,NaN,pnb,22.22,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
3,2019-11-01 00:00:11 UTC,cart,5876812,1487580010100293687,NaN,jessnail,3.16,564506666,186c1951-8052-4b37-adce-dd9644b1d5f7
4,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4635837 entries, 0 to 4635836
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 318.3 MB

In [7]:
df1.describe()

         product_id   category_id         price       user_id
count  4.635837e+06  4.635837e+06  4.635837e+06  4.635837e+06
mean   5.481406e+06  1.550049e+18  8.120701e+00  5.068070e+08
std    1.305582e+06  1.642371e+17  1.879197e+01  8.504375e+07
min    3.752000e+03  1.487580e+18 -7.937000e+01  1.120748e+06
25%    5.723529e+06  1.487580e+18  1.940000e+00  4.698573e+08
50%    5.810145e+06  1.487580e+18  3.970000e+00  5.421750e+08
75%    5.856186e+06  1.487580e+18  6.350000e+00  5.680491e+08
max    5.909246e+06  2.195085e+18  3.277800e+02  5.799699e+08

In [8]:
df1.isna().sum()

event_time             0
event_type             0
product_id             0
category_id            0
category_code    4560089
brand            1986029
price                  0
user_id                0
user_session         813
dtype: int64

In [10]:
missing_summary = pd.DataFrame({
    "missing_values":df1.isna().sum(),
    "missing_percent":(df1.isna().mean()*100.0).round(2)
})
missing_summary

               missing_values  missing_percent
event_time                  0             0.00
event_type                  0             0.00
product_id                  0             0.00
category_id                 0             0.00
category_code         4560089            98.37
brand                 1986029            42.84
price                       0             0.00
user_id                     0             0.00
user_session              813             0.02

In [11]:
df1.duplicated().sum()

np.int64(246693)

In [12]:
df1[df1.duplicated()]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
5,2019-11-01 00:00:24 UTC,remove_from_cart,5826182,1487580007483048900,NaN,NaN,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb
91,2019-11-01 00:06:22 UTC,remove_from_cart,5826980,1487580005671109489,NaN,masura,3.95,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f
161,2019-11-01 00:13:16 UTC,remove_from_cart,5749153,1487580007592100809,NaN,NaN,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
163,2019-11-01 00:13:17 UTC,remove_from_cart,5749156,1487580007592100809,NaN,NaN,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
174,2019-11-01 00:13:39 UTC,remove_from_cart,5804460,1783999063574708423,NaN,bluesky,19.05,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf
...,...,...,...,...,...,...,...,...,...
4635730,2019-11-30 23:56:08 UTC,remove_from_cart,5700047,1487580009286598681,NaN,runail,0.40,579966747,1512be50-d0fd-4a92-bcd8-3ea3943f2a3b
4635773,2019-11-30 23:57:31 UTC,cart,5670333,1487580006484804506,NaN,NaN,11.03,494077766,c99a50e8-2fac-4c4d-89ec-41c05f114554
4635824,2019-11-30 23:59:24 UTC,remove_from_cart,5608703,1487580005553668971,NaN,NaN,9.52,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635827,2019-11-30 23:59:25 UTC,remove_from_cart,5810080,1487580005268456287,NaN,irisk,6.51,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e
4635829,2019-11-30 23:59:27 UTC,remove_from_cart,5801131,1487580005486560104,NaN,irisk,3.65,566513990,b5053009-b3c4-4581-b05f-6199d1a2037e

In [14]:
df1["event_time"]=pd.to_datetime(df1["event_time"],
format='mixed',
dayfirst=True,
errors='coerce')

In [15]:
df1["event_time"].dtypes

datetime64[us, UTC]

In [16]:
df1["event_time_ist"] = df1["event_time"].dt.tz_convert("Asia/Kolkata")
df1["year"] = df1["event_time_ist"].dt.year
df1["month"] = df1["event_time_ist"].dt.month
df1["day_name"] = df1["event_time_ist"].dt.day_name()
df1["hour"] = df1["event_time_ist"].dt.hour
df1["minute"] = df1["event_time_ist"].dt.minute

In [17]:
df1 = df1.drop("category_code",axis=1)

In [18]:
df1 = df1.drop("event_time",axis=1)

In [19]:
df1["brand"].value_counts(dropna=False).head()

brand
NaN        1986029
runail      324850
irisk       204158
grattol     203487
masura      187542
Name: count, dtype: int64

In [20]:
df1["brand"].isna().mean()*100.0

np.float64(42.84078581710272)

In [21]:
df1["brand"]=df1["brand"].fillna("unknown")

In [22]:
df1.duplicated().sum()

np.int64(246693)

In [23]:
df1.isna().sum()

event_type          0
product_id          0
category_id         0
brand               0
price               0
user_id             0
user_session      813
event_time_ist      0
year                0
month               0
day_name            0
hour                0
minute              0
dtype: int64

In [26]:
df1[df1.duplicated()].head(50)

,event_type,product_id,category_id,brand,price,user_id,user_session,event_time_ist,year,month,day_name,hour,minute
5,remove_from_cart,5826182,1487580007483048900,unknown,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb,2019-01-11 05:30:24+05:30,2019,1,Friday,5,30
91,remove_from_cart,5826980,1487580005671109489,masura,3.95,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f,2019-01-11 05:36:22+05:30,2019,1,Friday,5,36
161,remove_from_cart,5749153,1487580007592100809,unknown,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:43:16+05:30,2019,1,Friday,5,43
163,remove_from_cart,5749156,1487580007592100809,unknown,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:43:17+05:30,2019,1,Friday,5,43
174,remove_from_cart,5804460,1783999063574708423,bluesky,19.05,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:43:39+05:30,2019,1,Friday,5,43
183,remove_from_cart,5768787,1487580005268456287,unknown,17.46,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:44:16+05:30,2019,1,Friday,5,44
188,remove_from_cart,5749148,1487580007592100809,unknown,0.22,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:44:38+05:30,2019,1,Friday,5,44
190,remove_from_cart,5556130,1487580012096782476,unknown,11.75,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:44:40+05:30,2019,1,Friday,5,44
193,remove_from_cart,5847347,1487580005092295511,unknown,6.51,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:44:43+05:30,2019,1,Friday,5,44
195,remove_from_cart,5847287,1982860244379763042,unknown,7.14,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:44:44+05:30,2019,1,Friday,5,44
198,remove_from_cart,5883341,1487580005461394279,bluesky,9.52,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:44:56+05:30,2019,1,Friday,5,44
200,remove_from_cart,5865126,1648815651034235876,rosi,4.13,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:02+05:30,2019,1,Friday,5,45
204,remove_from_cart,5768786,1487580007432717250,unknown,4.60,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:08+05:30,2019,1,Friday,5,45
211,remove_from_cart,5655420,1487580007046841266,unknown,5.56,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:25+05:30,2019,1,Friday,5,45
213,remove_from_cart,5692914,1487580007021675441,lianail,5.24,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:29+05:30,2019,1,Friday,5,45
217,remove_from_cart,5875325,1487580007214613434,unknown,2.51,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:32+05:30,2019,1,Friday,5,45
219,remove_from_cart,5818487,1487580007214613434,unknown,3.14,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:36+05:30,2019,1,Friday,5,45
221,remove_from_cart,5733824,1487580005050352469,haruyama,3.97,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:51+05:30,2019,1,Friday,5,45
223,remove_from_cart,5726164,1487580005595612013,unknown,3.00,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:54+05:30,2019,1,Friday,5,45
225,remove_from_cart,24392,1487580009227878422,depilflax,12.13,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:45:57+05:30,2019,1,Friday,5,45
227,remove_from_cart,5773382,1487580005134238553,runail,2.78,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:46:01+05:30,2019,1,Friday,5,46
229,remove_from_cart,5549814,1487580005595612013,unknown,3.00,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:46:17+05:30,2019,1,Friday,5,46
232,remove_from_cart,5886199,1783999068867920626,unknown,6.35,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:46:28+05:30,2019,1,Friday,5,46
235,remove_from_cart,5886200,1783999068909863670,unknown,3.17,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:46:30+05:30,2019,1,Friday,5,46
237,remove_from_cart,5886201,1783999068909863670,unknown,3.17,202438687,8dc848f5-bac3-44d7-9414-75d4e599abaf,2019-01-11 05:46:31+05:30,2019,1,Friday,5,46
259,remove_from_cart,5803689,1783999072332415142,unknown,12.22,562896848,152c88fe-862f-4373-8f2a-38bf9d67f8c7,2019-01-11 05:49:24+05:30,2019,1,Friday,5,49
335,remove_from_cart,5812118,1487580013212467384,art-visage,5.16,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 05:56:46+05:30,2019,1,Friday,5,56
420,remove_from_cart,5864463,1597770225539875791,unknown,19.05,565876667,cf5d7069-7465-4ec5-a9be-c911bc1b9f95,2019-01-11 06:01:50+05:30,2019,1,Friday,6,1
422,remove_from_cart,5746054,1487580006409307030,airnails,2.86,465774735,f8ab73fb-2bf1-4fce-bd7e-20c7bda55da4,2019-01-11 06:01:59+05:30,2019,1,Friday,6,1
426,remove_from_cart,5687864,1487580006409307030,airnails,2.86,465774735,f8ab73fb-2bf1-4fce-bd7e-20c7bda55da4,2019-01-11 06:02:06+05:30,2019,1,Friday,6,2
437,remove_from_cart,5812126,1542195323827388674,art-visage,4.05,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:02:55+05:30,2019,1,Friday,6,2
445,remove_from_cart,5878993,1487580013254410426,unknown,4.76,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:04:00+05:30,2019,1,Friday,6,4
448,remove_from_cart,5825979,1487580013254410426,unknown,1.19,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:04:04+05:30,2019,1,Friday,6,4
459,remove_from_cart,5885831,1487580013254410426,provoc,7.00,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:05:11+05:30,2019,1,Friday,6,5
462,remove_from_cart,5899871,1487580013338296510,unknown,4.71,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:05:34+05:30,2019,1,Friday,6,5
477,remove_from_cart,5784904,1487580010318397504,unknown,6.13,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:06:35+05:30,2019,1,Friday,6,6
480,remove_from_cart,5649305,1487580010335174721,concept,6.03,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:06:37+05:30,2019,1,Friday,6,6
493,remove_from_cart,5816172,1602943681873052386,grattol,5.24,520913926,8cbb5d91-80ba-45f8-b1bd-401b7b1dfa52,2019-01-11 06:07:11+05:30,2019,1,Friday,6,7
514,remove_from_cart,5868796,1783999064103190764,cosmoprofi,19.05,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:09:20+05:30,2019,1,Friday,6,9
524,remove_from_cart,5375,1487580006132482952,runail,1.35,539265551,97e8eb35-ebf1-4abd-9d44-351d10c930eb,2019-01-11 06:09:49+05:30,2019,1,Friday,6,9
542,remove_from_cart,5747405,1487580005671109489,masura,6.33,465774735,f8ab73fb-2bf1-4fce-bd7e-20c7bda55da4,2019-01-11 06:11:36+05:30,2019,1,Friday,6,11
572,remove_from_cart,5824821,1487580009445982239,domix,1.30,426101171,834073a4-0f8a-4cd0-b0d2-fa4bad58064c,2019-01-11 06:13:04+05:30,2019,1,Friday,6,13
583,remove_from_cart,5893947,1487580007172670392,masura,12.68,426101171,834073a4-0f8a-4cd0-b0d2-fa4bad58064c,2019-01-11 06:13:38+05:30,2019,1,Friday,6,13
687,remove_from_cart,5838787,1487580013522845895,irisk,0.54,469589164,220c422d-1a7a-401b-8929-322ecb0b8a39,2019-01-11 06:18:15+05:30,2019,1,Friday,6,18
715,remove_from_cart,5732031,1487580012574933146,domix,7.54,549007912,4cf9862d-8143-45b8-a034-36f4cc4206dd,2019-01-11 06:19:23+05:30,2019,1,Friday,6,19
722,remove_from_cart,5743449,1487580012574933146,unknown,6.03,549007912,4cf9862d-8143-45b8-a034-36f4cc4206dd,2019-01-11 06:19:31+05:30,2019,1,Friday,6,19
799,remove_from_cart,59974,1487580012096782476,unknown,7.14,374453476,18bd3f54-4603-43a1-977d-0697fdf776c9,2019-01-11 06:24:13+05:30,2019,1,Friday,6,24
839,remove_from_cart,5787008,1487580006644188066,unknown,6.33,426101171,834073a4-0f8a-4cd0-b0d2-fa4bad58064c,2019-01-11 06:26:21+05:30,2019,1,Friday,6,26
874,remove_from_cart,5550042,1487580005595612013,unknown,3.00,374453476,18bd3f54-4603-43a1-977d-0697fdf776c9,2019-01-11 06:28:17+05:30,2019,1,Friday,6,28
886,remove_from_cart,5550032,1487580005595612013,unknown,3.00,374453476,18bd3f54-4603-43a1-977d-0697fdf776c9,2019-01-11 06:28:44+05:30,2019,1,Friday,6,28

In [29]:
df1.duplicated().sum()

np.int64(246693)

In [30]:
df1 = df1.drop_duplicates()

In [31]:
df1.duplicated().sum()

np.int64(0)

In [32]:
df1.columns = df1.columns.str.strip().str.lower()

In [ ]:
df1[df1["price"]<0][
     ["event_type", "product_id", "price", "user_id", "user_session"]
    
]

,event_type,product_id,price,user_id,user_session
73174,purchase,5716855,-7.94,566480066,34fa4291-9e2e-470f-a678-b84d9bbbdfe3
330623,purchase,5716859,-47.62,567194545,fd27b149-3006-41cd-8afc-884c47272e5d
408236,purchase,5670257,-15.87,516725846,26e74f0c-762a-4162-b807-72a3e7bfa015
408237,purchase,5716857,-23.81,516725846,26e74f0c-762a-4162-b807-72a3e7bfa015
706884,purchase,5670257,-15.87,568159131,8edce83b-2d4c-4654-89e6-16234303031c
749942,purchase,5716861,-79.37,554241372,b85719db-2c56-460b-b800-d7a47d4c4d70
749943,purchase,5670257,-15.87,554241372,b85719db-2c56-460b-b800-d7a47d4c4d70
1372173,purchase,5716857,-23.81,549736485,d1acbc83-3876-4317-a00f-6c60800f4572
2310273,purchase,5716857,-23.81,565309368,47af9baa-94af-4334-a4ac-514230ddfa9c
2909975,purchase,5716859,-47.62,419166079,7e76a460-adb4-4e3f-9c85-c08a97016aa0
3093813,purchase,5716859,-47.62,540003383,33da1676-00df-4f21-b87e-4c1b9b09420c
3114212,purchase,5716857,-23.81,541269785,3d92c5f7-5d6d-4df6-83ad-6fcdb4078761
3306219,purchase,5716859,-47.62,574878046,b60c5299-7a53-e636-6dc3-c7fd5d86452b
3990421,purchase,5716855,-7.94,395032118,dad52920-321a-4d0d-805e-e83ff813d994
4340630,purchase,5670257,-15.87,569446220,14de64e5-bfbf-43e4-a3d9-362caf9f847e
4378008,purchase,5716857,-23.81,480927132,e2a0c787-1f5b-4bd6-b449-9818addd688f

In [37]:
(df1["price"]<0).sum()

np.int64(16)

In [38]:
df1.loc[df1["price"]<0,"price"] = np.nan

In [40]:
df1["price"] = df1["price"].fillna(df1.groupby("product_id")["price"].transform("median"));

In [41]:
df1.isna().sum()

event_type          0
product_id          0
category_id         0
brand               0
price              16
user_id             0
user_session      755
event_time_ist      0
year                0
month               0
day_name            0
hour                0
minute              0
dtype: int64

In [43]:
df1.dropna(subset=["user_session"],inplace=True)

In [44]:
df1.info()

<class 'pandas.DataFrame'>
Index: 4388389 entries, 0 to 4635836
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   event_type      str
 1   product_id      int64
 2   category_id     int64
 3   brand           str
 4   price           float64
 5   user_id         int64
 6   user_session    str
 7   event_time_ist  datetime64[us, Asia/Kolkata]
 8   year            int32
 9   month           int32
 10  day_name        str
 11  hour            int32
 12  minute          int32
dtypes: datetime64[us, Asia/Kolkata](1), float64(1), int32(4), int64(3), str(4)
memory usage: 401.8 MB

In [51]:
df1["brand"]=df1["brand"].str.strip()

In [53]:
df1["brand"].value_counts()

brand
unknown      1879673
runail        304861
grattol       192947
irisk         191319
masura        173276
              ...
shifei             3
dessata            2
macadamia          2
footlogix          2
ibd                1
Name: count, Length: 240, dtype: int64

In [54]:
df1.head()

,event_type,product_id,category_id,brand,price,user_id,user_session,event_time_ist,year,month,day_name,hour,minute
0,view,5802432,1487580009286598681,unknown,0.32,562076640,09fafd6c-6c99-46b1-834f-33527f4de241,2019-01-11 05:30:02+05:30,2019,1,Friday,5,30
1,cart,5844397,1487580006317032337,unknown,2.38,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb,2019-01-11 05:30:09+05:30,2019,1,Friday,5,30
2,view,5837166,1783999064103190764,pnb,22.22,556138645,57ed222e-a54a-4907-9944-5a875c2d7f4f,2019-01-11 05:30:10+05:30,2019,1,Friday,5,30
3,cart,5876812,1487580010100293687,jessnail,3.16,564506666,186c1951-8052-4b37-adce-dd9644b1d5f7,2019-01-11 05:30:11+05:30,2019,1,Friday,5,30
4,remove_from_cart,5826182,1487580007483048900,unknown,3.33,553329724,2067216c-31b5-455d-a1cc-af0575a34ffb,2019-01-11 05:30:24+05:30,2019,1,Friday,5,30

In [55]:
df1.describe()

,product_id,category_id,price,user_id,year,month,hour,minute
count,4.388389e+06,4.388389e+06,4.388373e+06,4.388389e+06,4388389.0,4.388389e+06,4.388389e+06,4.388389e+06
mean,5.478779e+06,1.550294e+18,8.308968e+00,5.071902e+08,2019.0,9.437615e+00,1.296213e+01,2.938751e+01
std,1.311047e+06,1.645476e+17,1.916128e+01,8.540806e+07,0.0,2.895257e+00,7.420313e+00,1.730415e+01
min,3.752000e+03,1.487580e+18,0.000000e+00,1.120748e+06,2019.0,1.000000e+00,0.000000e+00,0.000000e+00
25%,5.723529e+06,1.487580e+18,1.980000e+00,4.704789e+08,2019.0,9.000000e+00,7.000000e+00,1.400000e+01
50%,5.810145e+06,1.487580e+18,3.970000e+00,5.432802e+08,2019.0,1.100000e+01,1.500000e+01,2.900000e+01
75%,5.856186e+06,1.487580e+18,6.650000e+00,5.682251e+08,2019.0,1.100000e+01,1.900000e+01,4.400000e+01
max,5.909246e+06,2.195085e+18,3.277800e+02,5.799699e+08,2019.0,1.200000e+01,2.300000e+01,5.900000e+01

In [56]:
df1["price"].describe()

count    4.388373e+06
mean     8.308968e+00
std      1.916128e+01
min      0.000000e+00
25%      1.980000e+00
50%      3.970000e+00
75%      6.650000e+00
max      3.277800e+02
Name: price, dtype: float64

In [57]:
q1 = df1["price"].quantile(0.25)
q3 = df1["price"].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [58]:
outliers = df1[df1["price"]>upper_bound]
len(outliers)
len(outliers)/len(df1)*100.0

11.087645147228288

In [59]:
df1["price"].median()

np.float64(3.97)

In [61]:
outliers["price"].describe()

count    486569.000000
mean         42.646733
std          43.790906
min          13.670000
25%          17.300000
50%          23.810000
75%          49.210000
max         327.780000
Name: price, dtype: float64

In [62]:
outliers["price"].head(20)

2     22.22
6     15.71
12    15.71
14    14.76
15    15.71
19    15.08
29    15.81
32    17.46
33    22.54
36    20.16
43    57.14
48    18.38
51    20.16
52    25.71
53    15.71
55    15.71
56    15.71
59    13.75
60    29.21
80    32.54
Name: price, dtype: float64

In [63]:
outliers["price"].value_counts().head(20)

price
15.71     12331
19.52     12162
14.13     11811
16.03     10255
18.25      7494
44.29      7120
21.59      6153
14.29      6056
15.08      5822
16.67      4987
19.05      4734
17.46      4528
137.78     4471
21.43      4410
63.33      4354
18.89      4266
15.54      4253
122.22     4171
19.03      4084
194.44     4072
Name: count, dtype: int64

In [66]:
(df1["price"]==0).sum()
(df1["price"] == 0).mean() * 100

np.float64(0.2610297309559385)

In [68]:
df1[df1["price"]==0]["event_type"].value_counts()

event_type
view                8393
cart                2513
remove_from_cart     549
Name: count, dtype: int64

Price has no missing values. About 0.2% of records have zero price,
but these records are associated with view/cart/remove_from_cart events
and no purchases. IQR identified about 11% statistical outliers;
however, these prices occur repeatedly and are likely genuine product
prices. Therefore, price values are retained without removing outliers.

In [69]:
df1.isna().sum()

event_type         0
product_id         0
category_id        0
brand              0
price             16
user_id            0
user_session       0
event_time_ist     0
year               0
month              0
day_name           0
hour               0
minute             0
dtype: int64

In [70]:
df1.shape

(4388389, 13)

In [71]:
df1.to_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Nov.csv")

In [72]:
df1.columns.to_list()

['event_type',
 'product_id',
 'category_id',
 'brand',
 'price',
 'user_id',
 'user_session',
 'event_time_ist',
 'year',
 'month',
 'day_name',
 'hour',
 'minute']

In [80]:
df1 = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Nov.csv")

In [82]:
df1["event_time_ist"] = pd.to_datetime(df1["event_time_ist"])

df1.to_csv(
    "C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Nov.csv",
    index=False
)

In [85]:
df1=pd.read_csv(
    "C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Nov.csv",
    parse_dates=["event_time_ist"]
)

In [86]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4388389 entries, 0 to 4388388
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0      int64
 1   event_type      str
 2   product_id      int64
 3   category_id     int64
 4   brand           str
 5   price           float64
 6   user_id         int64
 7   user_session    str
 8   event_time_ist  datetime64[us, UTC+05:30]
 9   year            int64
 10  month           int64
 11  day_name        str
 12  hour            int64
 13  minute          int64
dtypes: datetime64[us, UTC+05:30](1), float64(1), int64(8), str(4)
memory usage: 468.7 MB

In [87]:
df1 = df1.drop(columns=["Unnamed: 0"])

In [88]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4388389 entries, 0 to 4388388
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   event_type      str
 1   product_id      int64
 2   category_id     int64
 3   brand           str
 4   price           float64
 5   user_id         int64
 6   user_session    str
 7   event_time_ist  datetime64[us, UTC+05:30]
 8   year            int64
 9   month           int64
 10  day_name        str
 11  hour            int64
 12  minute          int64
dtypes: datetime64[us, UTC+05:30](1), float64(1), int64(7), str(4)
memory usage: 435.2 MB

In [90]:
df1.to_csv(
    "C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Nov.csv",
    index=False
)

In [1]:
import pandas as pd 
import numpy as np
df1 = pd.read_csv("C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Nov.csv",parse_dates=["event_time_ist"]);
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4388389 entries, 0 to 4388388
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   event_type      str
 1   product_id      int64
 2   category_id     int64
 3   brand           str
 4   price           float64
 5   user_id         int64
 6   user_session    str
 7   event_time_ist  datetime64[us, UTC+05:30]
 8   year            int64
 9   month           int64
 10  day_name        str
 11  hour            int64
 12  minute          int64
dtypes: datetime64[us, UTC+05:30](1), float64(1), int64(7), str(4)
memory usage: 435.2 MB

In [3]:
df2.shape

(3533286, 9)

In [4]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 242.6 MB

In [3]:
df2.describe()

         product_id   category_id         price       user_id
count  3.533286e+06  3.533286e+06  3.533286e+06  3.533286e+06
mean   5.473054e+06  1.555023e+18  8.871856e+00  5.223318e+08
std    1.331331e+06  1.689262e+17  1.986474e+01  8.494819e+07
min    3.752000e+03  1.487580e+18 -7.937000e+01  1.180452e+06
25%    5.726191e+06  1.487580e+18  2.060000e+00  4.866830e+08
50%    5.811429e+06  1.487580e+18  4.210000e+00  5.566496e+08
75%    5.859462e+06  1.487580e+18  7.140000e+00  5.828019e+08
max    5.917178e+06  2.235524e+18  3.277800e+02  5.954145e+08

In [4]:
missing_summary = pd.DataFrame({
    "missing_values":df2.isna().sum(),
    "missing_percent":(df2.isna().mean()*100.0).round(2)
})
missing_summary

               missing_values  missing_percent
event_time                  0             0.00
event_type                  0             0.00
product_id                  0             0.00
category_id                 0             0.00
category_code         3474821            98.35
brand                 1510289            42.74
price                       0             0.00
user_id                     0             0.00
user_session              779             0.02

In [5]:
df2.drop("category_code",axis=1,inplace=True)

In [6]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   event_time    str
 1   event_type    str
 2   product_id    int64
 3   category_id   int64
 4   brand         str
 5   price         float64
 6   user_id       int64
 7   user_session  str
dtypes: float64(1), int64(3), str(4)
memory usage: 215.7 MB

In [7]:
df2["event_time"]=pd.to_datetime(df2["event_time"],
                                 format='mixed',
                                 dayfirst=True,
                                 errors='coerce')
df2["month"] = df2["event_time"].dt.month
df2["day"] = df2["event_time"].dt.day
df2["day_of_week"] = df2["event_time"].dt.day_name()
df2["hour"] = df2["event_time"].dt.hour
df2["minute"] = df2["event_time"].dt.minute

In [8]:
df2["event_time"].dtypes

datetime64[us, UTC]

In [9]:
df2["brand"]=df2["brand"].fillna("unknown")

In [12]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3533286 entries, 0 to 3533285
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   event_time    datetime64[us, UTC]
 1   event_type    str
 2   product_id    int64
 3   category_id   int64
 4   brand         str
 5   price         float64
 6   user_id       int64
 7   user_session  str
 8   month         int32
 9   day           int32
 10  day_of_week   str
 11  hour          int32
 12  minute        int32
dtypes: datetime64[us, UTC](1), float64(1), int32(4), int64(3), str(4)
memory usage: 296.5 MB

In [13]:
df2.isna().sum()

event_time        0
event_type        0
product_id        0
category_id       0
brand             0
price             0
user_id           0
user_session    779
month             0
day               0
day_of_week       0
hour              0
minute            0
dtype: int64

In [14]:
df2.duplicated().sum()

np.int64(183860)

In [10]:
df2.dropna(subset="user_session",inplace=True)

In [16]:
df2.isna().sum()

event_time      0
event_type      0
product_id      0
category_id     0
brand           0
price           0
user_id         0
user_session    0
month           0
day             0
day_of_week     0
hour            0
minute          0
dtype: int64

In [18]:
df2[df2.duplicated()]

,event_time,event_type,product_id,category_id,brand,price,user_id,user_session,month,day,day_of_week,hour,minute
37,2019-01-12 00:01:52+00:00,cart,5700046,1487580009286598681,runail,0.40,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc,1,12,Saturday,0,1
55,2019-01-12 00:02:49+00:00,cart,5693501,1487580009445982239,unknown,0.60,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d,1,12,Saturday,0,2
61,2019-01-12 00:03:08+00:00,remove_from_cart,5859482,1487580005671109489,masura,1.60,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6,1,12,Saturday,0,3
62,2019-01-12 00:03:08+00:00,remove_from_cart,5839671,1487580005671109489,masura,2.19,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6,1,12,Saturday,0,3
66,2019-01-12 00:03:10+00:00,remove_from_cart,5859482,1487580005671109489,masura,1.60,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6,1,12,Saturday,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533102,2019-12-31 23:41:36+00:00,remove_from_cart,5814042,1783999063314661546,grattol,10.32,538536440,a6c0568e-026b-4147-9747-02956061596c,12,31,Tuesday,23,41
3533159,2019-12-31 23:47:12+00:00,remove_from_cart,5829508,1487580012096782476,farmstay,4.03,355374962,1a0088ea-20b1-4788-b642-44f982881778,12,31,Tuesday,23,47
3533172,2019-12-31 23:48:49+00:00,remove_from_cart,5917159,1783999072332415142,herbolive,21.83,355374962,1a0088ea-20b1-4788-b642-44f982881778,12,31,Tuesday,23,48
3533185,2019-12-31 23:50:26+00:00,remove_from_cart,5809910,1602943681873052386,grattol,5.24,459117441,801a753b-912f-4a0f-9f99-9c90419be144,12,31,Tuesday,23,50
3533261,2019-12-31 23:57:22+00:00,remove_from_cart,5893695,1487580011585077370,ecocraft,6.97,588166646,e099adca-fec5-4aef-820f-6116836e322a,12,31,Tuesday,23,57

In [19]:
df2["brand"].value_counts(dropna=False)

brand
unknown      1510012
runail        256159
grattol       155873
irisk         152497
masura        125178
              ...
ikoo               3
ibd                1
macadamia          1
shifei             1
dessata            1
Name: count, Length: 253, dtype: int64

In [21]:
df2[df2.duplicated(keep=False)].sort_values(["event_time","user_session"]).head()

,event_time,event_type,product_id,category_id,brand,price,user_id,user_session,month,day,day_of_week,hour,minute
36,2019-01-12 00:01:52+00:00,cart,5700046,1487580009286598681,runail,0.40,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc,1,12,Saturday,0,1
37,2019-01-12 00:01:52+00:00,cart,5700046,1487580009286598681,runail,0.40,576802932,51d85cb0-897f-48d2-918b-ad63965c12dc,1,12,Saturday,0,1
54,2019-01-12 00:02:49+00:00,cart,5693501,1487580009445982239,unknown,0.60,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d,1,12,Saturday,0,2
55,2019-01-12 00:02:49+00:00,cart,5693501,1487580009445982239,unknown,0.60,579751441,8de492d7-0937-47ae-be2c-a7615aec2b0d,1,12,Saturday,0,2
59,2019-01-12 00:03:08+00:00,remove_from_cart,5839671,1487580005671109489,masura,2.19,561162056,39cf2227-03ed-421e-9615-7814b9b3c5e6,1,12,Saturday,0,3

In [22]:
df2 = df2.drop_duplicates()

In [23]:
df2.duplicated().sum()

np.int64(0)

In [24]:
df2.columns  = df2.columns.str.strip().str.lower()

In [25]:
df2["price"] =df2["price"].fillna(df2.groupby("product_id")["price"].transform('median'))

In [27]:
df2.isna().sum()

event_time      0
event_type      0
product_id      0
category_id     0
brand           0
price           0
user_id         0
user_session    0
month           0
day             0
day_of_week     0
hour            0
minute          0
dtype: int64

In [28]:
df2.duplicated().sum()

np.int64(0)

In [12]:
df2.loc[df2["price"] < 0, "price"] = np.nan

In [30]:
df2["price"] =df2["price"].fillna(df2.groupby("product_id")["price"].transform('median'))

In [13]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3532507 entries, 0 to 3533285
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   event_time    datetime64[us, UTC]
 1   event_type    str
 2   product_id    int64
 3   category_id   int64
 4   brand         str
 5   price         float64
 6   user_id       int64
 7   user_session  str
 8   month         int32
 9   day           int32
 10  day_of_week   str
 11  hour          int32
 12  minute        int32
dtypes: datetime64[us, UTC](1), float64(1), int32(4), int64(3), str(4)
memory usage: 323.4 MB

In [14]:
df2.isna().sum()

event_time       0
event_type       0
product_id       0
category_id      0
brand            0
price           18
user_id          0
user_session     0
month            0
day              0
day_of_week      0
hour             0
minute           0
dtype: int64

In [33]:
df2["price"].isna().mean()*100.0

np.float64(100.0)

In [15]:
print(df2["price"].head(20))
print("Min:", df2["price"].min())
print("Max:", df2["price"].max())
print("Negative:", (df2["price"] < 0).sum())

0      6.27
1     29.05
2      1.19
3      0.79
4      5.56
5      2.62
6      1.19
7      4.44
8      5.40
9      0.40
10     2.79
11     3.33
12     2.79
13     6.35
14     6.19
15     2.79
16     3.65
17    10.95
18     2.86
19     2.86
Name: price, dtype: float64
Min: 0.0
Max: 327.78
Negative: 0

In [16]:
df2.describe()

,product_id,category_id,price,user_id,month,day,hour,minute
count,3.532507e+06,3.532507e+06,3.532489e+06,3.532507e+06,3.532507e+06,3.532507e+06,3.532507e+06,3.532507e+06
mean,5.473045e+06,1.555023e+18,8.872178e+00,5.223249e+08,9.551995e+00,1.681851e+01,1.318369e+01,2.966688e+01
std,1.331346e+06,1.689255e+17,1.986525e+01,8.495066e+07,3.572426e+00,5.790800e+00,5.519528e+00,1.728983e+01
min,3.752000e+03,1.487580e+18,0.000000e+00,1.180452e+06,1.000000e+00,1.200000e+01,0.000000e+00,0.000000e+00
25%,5.726190e+06,1.487580e+18,2.060000e+00,4.866830e+08,7.000000e+00,1.200000e+01,9.000000e+00,1.500000e+01
50%,5.811429e+06,1.487580e+18,4.210000e+00,5.566178e+08,1.200000e+01,1.400000e+01,1.300000e+01,3.000000e+01
75%,5.859462e+06,1.487580e+18,7.140000e+00,5.828001e+08,1.200000e+01,2.100000e+01,1.800000e+01,4.500000e+01
max,5.917178e+06,2.235524e+18,3.277800e+02,5.954145e+08,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01

In [24]:
df2["price"].max()

np.float64(327.78)

In [17]:
Q1 = df2["price"].quantile(0.25)
Q3 = df2["price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower)
print("Upper limit:", upper)

Q1: 2.06
Q3: 7.14
IQR: 5.08
Lower limit: -5.5600000000000005
Upper limit: 14.76

In [18]:
outliers = df2[df2["price"] > upper]

print("Total outliers:", len(outliers))
print(outliers["price"].sort_values(ascending=False).head(20))

Total outliers: 391409
944169     327.78
231290     327.78
130577     327.78
2412793    327.78
1902514    327.78
2115161    327.78
94205      327.78
972383     327.78
1478352    327.78
1411596    327.78
2180612    327.78
1479518    327.78
429659     327.78
1732052    327.78
3459454    327.78
695692     327.78
695629     327.78
932868     327.78
1195043    327.78
663213     327.78
Name: price, dtype: float64

In [19]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3532507 entries, 0 to 3533285
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   event_time    datetime64[us, UTC]
 1   event_type    str
 2   product_id    int64
 3   category_id   int64
 4   brand         str
 5   price         float64
 6   user_id       int64
 7   user_session  str
 8   month         int32
 9   day           int32
 10  day_of_week   str
 11  hour          int32
 12  minute        int32
dtypes: datetime64[us, UTC](1), float64(1), int32(4), int64(3), str(4)
memory usage: 323.4 MB

In [20]:
df2.isna().sum()

event_time       0
event_type       0
product_id       0
category_id      0
brand            0
price           18
user_id          0
user_session     0
month            0
day              0
day_of_week      0
hour             0
minute           0
dtype: int64

In [23]:
df2.duplicated().sum()

np.int64(0)

In [25]:
median_price = df2["price"].median()

In [26]:
df2["price"]=df2["price"].fillna(median_price)

In [28]:
df2["price"].isna().sum()

np.int64(0)

In [29]:
df2.to_csv(
    "C:/Users/hp/Documents/Cart Abandonment Pattern Analysis/data/cleaned_data/2019-Dec.csv",
    index=False
)

In [31]:
print(df3.shape);
print(df4.shape);

(4264752, 9)
(4156682, 9)

In [32]:
print(df3.info());
print(df4.info());

<class 'pandas.DataFrame'>
RangeIndex: 4264752 entries, 0 to 4264751
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 292.8 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 4156682 entries, 0 to 4156681
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 285.4 MB
None

In [33]:
df3["event_time"]=pd.to_datetime(df3["event_time"],
                                 format='mixed',
                                 dayfirst=True,
                                 errors='coerce')
df3["month"] = df3["event_time"].dt.month
df3["day"] = df3["event_time"].dt.day
df3["day_of_week"] = df2["event_time"].dt.day_name()
df3["hour"] = df3["event_time"].dt.hour
df3["minute"] = df3["event_time"].dt.minute

df4["event_time"]=pd.to_datetime(df4["event_time"],
                                 format='mixed',
                                 dayfirst=True,
                                 errors='coerce')
df4["month"] = df4["event_time"].dt.month
df4["day"] = df4["event_time"].dt.day
df4["day_of_week"] = df4["event_time"].dt.day_name()
df4["hour"] = df4["event_time"].dt.hour
df4["minute"] = df4["event_time"].dt.minute

In [36]:
df3.isna().sum()

event_time             0
event_type             0
product_id             0
category_id            0
category_code    4190033
brand            1775630
price                  0
user_id                0
user_session        1314
month                  0
day                    0
day_of_week       916040
hour                   0
minute                 0
dtype: int64